### PR TITLE
Development integration concurrent gittools

### PR DESCRIPTION
**Pull request by mariobassem**

### CODE REVIEW

**Comment by timurgordon** [comment]
Hero doesn't compile due to some weird v error. seems to do with locking the global redis_client

**Comment by timurgordon** [comment]
git list uses concurrency when loading git structure but not when formatting output per repo which also takes some time because it fetches realtime git status (cant rely on caches sinces must check for unstaged changes etc)

**Comment by timurgordon** [comment]
Performance comparison with concurrency for codebase with 33 repositories:

| Git List Type       | With Concurrency | Without Concurrency|
|-----------------|--------------------|---------------------|
| Uncached          | 71 seconds             | 179 seconds             |
| Cached              | 1 second                 | 23 seconds              |

**Comment by despiegk** [comment]
list should use cache, not from filesystem

**Pull request merged**
